### ISSUE TITLE
Проблемы на win10 x64

### ISSUE THREAD

**Issue by vitaly7657** [corax4/JoySave#1]
Доброго времени суток. Не могу в поля Сайт, Путь и Файл вписать текс, либо вставить скопированный текст. Платформа win 10 x64. В аналогичном поле куки всё вписывается. Скомпилировать прогу не смог, ругается на HTTPsend.

![js](https://user-images.githubusercontent.com/108196567/193443449-eaf38978-fa70-4124-aec6-9dec54dc1de0.png)

**Comment by corax4** [comment]
Здравствуйте. В эти поля не нужно ничего вводить - они только для отображения. Они заполняются сами во время работы, на основе данных из таблицы. Насколько помню, там есть всплывающие подсказки по ним, и по таблице, и почти по всему остальному.
По поводу компиляции - посмотрите, пожалуйста, readme. Для компиляции нужно в папку с проектом положить папку с пакетом synapse. Так же в readme описанно какие изменения я вносил в synapse (всего несколько строк, да и те только для linux имеют значение). 
Если Вы желаете скомпилировать, то проще исходники взять из самой программы. Это программа-черепашка, она носит всё с собой :-) Запустите её с параметром sources (joysave.exe sources). Тогда исходники будут сохранены вместе с программой, в т.ч. пакет synapse с изменениями). Так же чтоб программа скомпилировалась, среди исходников должен быть архив с исходниками с именем sources.zip. Его создает bat-файл sources.bat с использованием 7-zip, или переименуйте архив с исходниками, которую создает прога. Так же нужен архив с библиотеками ssl. Программа при сохранении исходников создает и его, или скачайте его с guthub по ссылке из readme. 
При компиляции под windows поставьте в настройках проекта целевую платформу i386, так как библиотеки именно для этой платформы (при этом программа будет работать как на x64, так и на x86). При этом нужно чтобы у Вас был установлен кросс-компилятор x86-x64. Либо целевую платформу можно не менять и компилировать в 32-хразрядной версии Lazarus. 
Если возникнут сложности - постараюсь Вам помочь :-)

**Comment by vitaly7657** [comment]
Спасибо за развёрнутый ответ. Всё получилось.
