### ISSUE TITLE
Запуск на Mac

### ISSUE THREAD

**Issue by Halvanhelv** [corax4/JoySave#2]
Можно ли как то запустить на Mac?

**Comment by corax4** [comment]
> Можно ли как то запустить на Mac?

Думаю что если чуть подредактировать то можно скомпилировать для Mac. 
Но увы у меня нет и никогда не было Mac. И времени сейчас пока нет.

**Comment by corax4** [comment]
> Можно ли как то запустить на Mac?

Теперь есть версия для Mac!
